# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20181209_1720'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.Department'),
            preserve_default=False,
        ),
    ]
