# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20181209_1720'),
        ('profiles', '0002_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='faculty',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.Faculty'),
            preserve_default=False,
        ),
    ]
