# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Course',
        ),
    ]
