# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20181209_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='subject',
            new_name='course',
        ),
    ]
