# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20181209_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('midterm', 'Midterm'), ('f', 'Final')], max_length=255),
        ),
    ]
